### PR TITLE
PHP 8 support

### LINKED ISSUE #19: PHP 8 - Method ReflectionParameter::getClass() is deprecated
Hi Matthieu,

PHP 8 deprecates the `ReflectionParameter::getClass()` method, and suggests the usage of `ReflectionParameter::getType()`. This causes problems (and a slight performance penalty) to PHP-DI.

### PR DESCRIPTION
**Pull request by mnapoli**
Fix #19

This PR introduces PHP 8 support.

It now requires PHP 7.2 and up.

### CODE REVIEW

**Comment by williamdes** [comment]
Bonjour @mnapoli 
You did forget to update the `.gitattributes` file ;)

**Comment by mnapoli** [comment]
@williamdes I'm not sure what you mean by that?

**Comment by williamdes** [comment]
> @williamdes I'm not sure what you mean by that?

I mean that https://github.com/PHP-DI/PhpDocReader/blob/66daff34cbd2627740ffec9469ffbac9f8c8185c/.gitattributes#L4

Should now be `.github`

**Comment by mnapoli** [comment]
oh ok yes

**Pull request merged**
